import { Roboto } from "next/font/google";
import "./global.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import "@ant-design/v5-patch-for-react-19";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  style: ["normal", "italic"],
  weight: ["100", "300", "400", "500", "700", "900"], // All font weights
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        <AntdRegistry>
          <ConfigProvider
            theme={{
              components: {
                Tabs: {
                  colorPrimary: "#C42026",
                  colorPrimaryHover: "#e6171f",
                  colorPrimaryActive: "#e6171f",
                },
              },
            }}
          >
            {children}
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}